name: Run PHP Token Generation Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: |
        sudo apt-get install php-curl
        composer install # If you have a composer.json file for dependencies

    - name: Run PHP script
      run: |
        php token_generation.php
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        AUTH_CODE: ${{ secrets.AUTH_CODE }}
