name: Google Sheets Access

on:
  push:
    branches:
      - main

jobs:
  access_google_sheets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests google-auth google-auth-oauthlib google-auth-httplib2
          pip install gspread
          pip gspread openai


      - name: Decode Google JSON Key
        env:
          GOOGLE_JSON_KEY_BASE64: ${{ secrets.GOOGLE_JSON_KEY_BASE64 }}
        run: |
          echo "Decoding Google JSON Key..."
          if [ -z "$GOOGLE_JSON_KEY_BASE64" ]; then
            echo "Error: GOOGLE_JSON_KEY_BASE64 is not set."
            exit 1
          fi
          echo "$GOOGLE_JSON_KEY_BASE64" | base64 --decode > /tmp/google-key.json
          echo "Google JSON Key decoded successfully."

      - name: Run Python script
        run: |
          python aliexpress_api.py
