name: Run Affiliate API Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'  # 매일 새벽 3시에 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install openai package
        run: |
          python -m pip install --upgrade pip
          pip install openai  # Install openai directly
      - name: Decode Google JSON Key
        run: |
          echo ${{ secrets.GOOGLE_JSON_KEY_BASE64 }} | base64 --decode > /tmp/google-key.json
      - name: Run script
        run: |
          export GOOGLE_JSON_KEY_PATH="/tmp/google-key.json"
          python aliexpress_api.py
