name: Run Affiliate API Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'  # 매일 새벽 3시에 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests gspread google-auth google-auth-oauthlib google-auth-httplib2

      - name: Decode Google JSON Key
        env:
          GOOGLE_JSON_KEY_BASE64: ${{ secrets.GOOGLE_JSON_KEY_BASE64 }}
        run: |
          # Base64로 인코딩된 Google JSON Key를 디코딩하여 /tmp/google-key.json 파일로 저장
          echo "$GOOGLE_JSON_KEY_BASE64" | base64 --decode > /tmp/google-key.json
  
      - name: Check GOOGLE_JSON_KEY_BASE64
        run: |
          echo "GOOGLE_JSON_KEY_BASE64 is set: ${GOOGLE_JSON_KEY_BASE64:+true}"

    
      - name: Run script
        run: |
          # 환경 변수로 Google JSON Key 경로 설정
          export GOOGLE_JSON_KEY_PATH="/tmp/google-key.json"
          
          # Python 스크립트 실행
          python aliexpress_api.py
