name: Run Affiliate API Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'  # 매일 새벽 3시에 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests gspread google-auth google-auth-oauthlib google-auth-httplib2

      - name: Debug Google JSON Key
        run: |
          echo "GOOGLE_JSON_KEY_BASE64: ${{ secrets.GOOGLE_JSON_KEY_BASE64 }}"

      - name: Decode Google JSON Key
        run: |
          if [ -z "${{ secrets.GOOGLE_JSON_KEY_BASE64 }}" ]; then
            echo "GOOGLE_JSON_KEY_BASE64 is empty"
            exit 1
          fi
          echo ${{ secrets.GOOGLE_JSON_KEY_BASE64 }} | base64 --decode > /tmp/google-key.json

      - name: Run script
        run: |
          export GOOGLE_JSON_KEY_PATH="/tmp/google-key.json"
          python aliexpress_api.py
