name: Run token generation script

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 리포지토리 체크아웃

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Python 3.8 설정

      - name: Install dependencies
        run: |
          pip install requests
          pip install PyGithub
          # GitHub에서 클론한 후, 경로 설정
          git clone https://github.com/jungsoonpark/pickview_lightsail.git
          cd pickview_lightsail/aliexpress_sdk/iop  # iop 디렉토리로 이동

      - name: Set up PYTHONPATH for iop SDK
        run: |
          echo "Setting up PYTHONPATH for iop SDK..."
          echo "PYTHONPATH=$(pwd)/pickview_lightsail/aliexpress_sdk/iop" >> $GITHUB_ENV  # iop 경로 추가

      - name: Run token generation script
        env:
          API_KEY: ${{ secrets.ALIEXPRESS_API_KEY }}  # GitHub Secrets에서 API_KEY 가져오기
          API_SECRET: ${{ secrets.ALIEXPRESS_API_SECRET }}  # GitHub Secrets에서 API_SECRET 가져오기
        run: |
          python token_generation.py  # 파이썬 스크립트 실행
